name: 每日新闻摘要

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4        # ← 别忘了加这个！

      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: 安装依赖
        run: pip install openai feedparser requests python-dotenv schedule groq

      - name: 运行程序
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
<<<<<<< HEAD
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        
        run: python main.py
=======
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python main.py
>>>>>>> dc7cc95bb0e49515ec329d1001f28ecfa74c9537
